from decimal import Decimal, ROUND_HALF_UP, ROUND_HALF_DOWN, ROUND_HALF_EVEN

v1 = Decimal(1.5)
v2 = Decimal(2.5)
v3 = Decimal(3.5)
o1 = Decimal(v1.quantize(1, rounding=ROUND_HALF_UP))
print(o1)
o2 = Decimal(v2.quantize(1, rounding=ROUND_HALF_UP))
print(o2)
o3 = Decimal(v3.quantize(1, rounding=ROUND_HALF_UP))
print(o3)
o4 = Decimal(v1.quantize(1, rounding=ROUND_HALF_DOWN))
print(o4)
o5 = Decimal(v2.quantize(1, rounding=ROUND_HALF_DOWN))
print(o5)
o6 = Decimal(v3.quantize(1, rounding=ROUND_HALF_DOWN))
print(o6)
o7 = Decimal(v1.quantize(1, rounding=ROUND_HALF_EVEN))
print(o7)
o8 = Decimal(v2.quantize(1, rounding=ROUND_HALF_EVEN))
print(o8)
o9 = Decimal(v3.quantize(1, rounding=ROUND_HALF_EVEN))
print(o9)
v4 = Decimal(5 / 3)
r1 = Decimal(v4.quantize(1))
print('r1=', r1)
r2 = Decimal(v4.quantize(Decimal('0.1')))
print('r2=', r2)
r3 = Decimal(v4.quantize(Decimal('0.01')))
print('r3=', r3)
