l1 = list('ABC')
l2 = list('ABC')
l3 = list('ABC')
l1.append('D')
l2.extend('D')
l3 += 'D'
print(l1)
print(l2)
print(l3)
l1.append(['E', 'F'])
print(l1)
l2.extend(['E', 'F'])
print(l2)
l3 += ['E', 'F']
print(l3)